server:
  port: 8081
logging:
  level:
    com.yjy: debug
jp:
  swagger:
    basePackage: com.yjy.controller
    apiInfo:
      title: demo
      description: demo
      version: 1.0.0
      email: 2864245248@qq.com
# 该配置的名称是固定的，不可以改变，否则将不能自动加载到数据源中
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://172.0.0.1:3306/t_pos?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8
    url: jdbc:mysql://localhost:3306/t_pos?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
 
